version: "3.8"
services:
  front:
    image: epsi-front
    restart: always
    container_name: front
    environment:
      TZ: Europe/Paris
    ports:
      - "4200:80"
  bff:
    image: epsi-bff
    restart: always
    container_name: bff
    depends_on:
      - microservice
    environment:
      TZ: Europe/Paris
      PATH_MICRO_SERVICE: http://microservice:8081
      USER: docker
      PASSWORD: docker
    ports:
      - "8080:8080"
  microservice:
    image: epsi-micro-service
    restart: always
    container_name: microservice
    environment:
      TZ: Europe/Paris
      DATABASE: docker
      USER: docker
      PASSWORD: docker
      PATH_DATABASE: db
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./bdd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 3001:80
