version: "3.8"
services:
  front:
    image: stephanparichon/epsi-front:1.0
    restart: always
    container_name: front
    environment:
      TZ: Europe/Paris
    ports:
      - "4200:80"
  bff:
    image: stephanparichon/epsi-bff:1.0
    restart: always
    container_name: bff
    environment:
      TZ: Europe/Paris
      PATH_MICRO_SERVICE: http://microservice:8081
      USER: docker
      PASSWORD: docker
    ports:
      - "8080:8080"
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./bdd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 3001:80
